a = Analysis(
    ['vueInit.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['multiprocessing', 'xml', 'IPython', 'PIL', 'sqlite3', 'pygments', 'aiobotocore', 'aiohttp', 'aioitertools', 'aiosignal', 'alabaster', 'altair', 'altgraph', 'anaconda-anon-usage', 'anaconda-catalogs', 'anaconda-client', 'anaconda-cloud-auth', 'anaconda-navigator', 'anaconda-project', 'ANSI_Define', 'ansi-escapes', 'ansi-styles', 'anyio', 'appdirs', 'archspec', 'argon2-cffi', 'argon2-cffi-bindings', 'arrow', 'astor', 'astroid', 'astropy', 'asttokens', 'async-lru', 'atomicwrites', 'attrs', 'Automat', 'autopep8', 'Babel', 'backports.functools-lru-cache', 'backports.tempfile', 'backports.weakref', 'bcrypt', 'beautifulsoup4', 'binaryornot', 'black', 'bleach', 'blinker', 'bokeh', 'boltons', 'botocore', 'Bottleneck', 'Brotli', 'build', 'cachetools', 'certifi', 'cffi', 'chardet', 'charset-normalizer',
    # 'click',
    'cloudpickle', 'clyent',
    # 'colorama',
    'colorcet', 'comm', 'conda', 'conda-build', 'conda-content-trust', 'conda_index', 'conda-libmamba-solver', 'conda-pack', 'conda-package-handling', 'conda_package_streaming', 'conda-repo-cli', 'conda-token', 'conda-verify', 'confunc', 'constantly', 'contourpy', 'cookiecutter', 'cryptography', 'cssselect', 'cssutils', 'cycler', 'Cython', 'cytoolz', 'dask', 'datashader', 'debugpy', 'decorator', 'defusedxml', 'Deprecated', 'dict', 'diff-match-patch', 'dill', 'distributed', 'distro', 'dnspython', 'docstring-to-markdown', 'docutils', 'entrypoints', 'et-xmlfile', 'executing', 'fastjsonschema', 'figureTools', 'filelock', 'flake8', 'Flask', 'fonttools', 'frozendict', 'frozenlist', 'fsspec', 'future', 'gensim', 'git-filter-repo', 'gitdb', 'GitPython', 'gmpy2', 'greenlet', 'h11', 'h5py', 'has-flag', 'HeapDict', 'holoviews', 'hvplot', 'hyperlink', 'idna', 'imagecodecs', 'imageio', 'imagesize', 'imbalanced-learn', 'importlib-metadata', 'incremental', 'inflection', 'iniconfig', 'intake', 'intel-openmp', 'intervaltree', 'ipykernel', 'ipython', 'ipython-genutils', 'ipywidgets', 'isort', 'itemadapter', 'itemloaders',
    # 'itsdangerous',
    'jaraco.classes', 'javascript', 'jedi', 'jellyfish', 'Jinja2', 'jmespath', 'joblib', 'Js2Py', 'json5', 'jsonpatch', 'jsonpointer', 'jsonschema', 'jsonschema-specifications', 'jupyter', 'jupyter_client', 'jupyter-console', 'jupyter_core', 'jupyter-events', 'jupyter-lsp', 'jupyter_server', 'jupyter_server_terminals', 'jupyterlab', 'jupyterlab-pygments', 'jupyterlab_server', 'jupyterlab-widgets', 'keyring', 'kiwisolver', 'lazy_loader', 'lazy-object-proxy', 'lckr_jupyterlab_variableinspector', 'libarchive-c', 'libmambapy', 'linkify-it-py', 'llvmlite', 'lmdb', 'locket', 'logTools', 'lxml', 'lz4', 'Markdown', 'markdown-it-py', 'MarkupSafe', 'matplotlib', 'matplotlib-inline', 'mccabe', 'mcpi', 'mcpi2', 'mcrcon', 'mdit-py-plugins', 'mdurl', 'menuinst', 'mistune', 'mkl', 'mkl-fft', 'mkl-random', 'mkl-service', 'more-itertools', 'mpld3', 'mpmath', 'msgpack', 'multidict', 'multipledispatch', 'munkres', 'mutf8', 'mypy', 'mypy-extensions', 'navigator-updater', 'nbclient', 'nbconvert', 'nbformat', 'nest-asyncio', 'netTools', 'networkx', 'nh3', 'nltk', 'notebook', 'notebook_shim', 'numba', 'numexpr', 'numpy', 'numpydoc', 'opencv-python', 'openpyxl', 'outcome', 'overrides', 'packaging', 'pandas', 'pandocfilters', 'panel', 'param', 'paramiko', 'parsel', 'parso', 'partd', 'pathspec', 'patsy', 'pefile', 'pexpect', 'pickleshare', 'pillow', 'pip', 'pkce', 'pkginfo', 'platformdirs', 'plotly', 'pluggy', 'ply', 'prometheus-client', 'prompt-toolkit', 'Protego', 'protobuf', 'psutil', 'ptioTools', 'ptyprocess', 'pure-eval', 'py-cpuinfo', 'pyarrow', 'pyasn1', 'pyasn1-modules', 'pyassimp', 'pybind11', 'pycodestyle', 'pycosat', 'pycparser', 'pyct', 'pycurl', 'pydantic', 'pydeck', 'PyDispatcher', 'pydocstyle', 'pyerfa', 'pyflakes', 'Pygments', 'pyinstaller', 'pyinstaller-hooks-contrib', 'pyjsparser', 'PyJWT', 'pylint', 'pylint-venv', 'pyls-spyder', 'PyMySQL', 'PyNaCl', 'PyNBT', 'pyodbc', 'pyOpenSSL', 'pyparsing', 'pyproject_hooks', 'PyQt5', 'PyQt5-sip', 'PyQt6', 'PyQt6-Qt6', 'PyQt6-sip', 'PyQtWebEngine', 'PySocks', 'pytest', 'python-dateutil', 'python-docx', 'python-dotenv', 'python-json-logger', 'python-lsp-black', 'python-lsp-jsonrpc', 'python-lsp-server', 'python-slugify', 'python-snappy', 'pytoolconfig', 'pytz', 'pyviz_comms', 'pywavelets', 'pywin32', 'pywin32-ctypes', 'pywinpty', 'PyYAML', 'pyzmq', 'QDarkStyle', 'qstylizer', 'QtAwesome', 'qtconsole', 'QtPy', 'queuelib', 'readme_renderer', 'referencing', 'regex', 'requests', 'requests-file', 'requests-toolbelt', 'rfc3339-validator', 'rfc3986', 'rfc3986-validator', 'rich', 'rope', 'rpds-py', 'Rtree', 'ruamel.yaml', 'ruamel-yaml-conda', 's3fs', 'scapy', 'scikit-image', 'scikit-learn', 'scipy', 'Scrapy', 'seaborn', 'selenium', 'semver', 'Send2Trash', 'service-identity', 'setuptools', 'setuptools-scm', 'sip', 'six', 'smart-open', 'smmap', 'sniffio', 'snowballstemmer', 'sortedcontainers', 'soupsieve', 'Sphinx', 'sphinxcontrib-applehelp', 'sphinxcontrib-devhelp', 'sphinxcontrib-htmlhelp', 'sphinxcontrib-jsmath', 'sphinxcontrib-qthelp', 'sphinxcontrib-serializinghtml', 'spiderTools', 'spyder', 'spyder-kernels', 'SQLAlchemy', 'sqlTools', 'stack-data', 'statsmodels', 'streamlit', 'supports-color', 'sympy', 'systemTools', 'tables', 'tabulate', 'tbb', 'tblib', 'tenacity', 'terminado', 'text-unidecode', 'textdistance', 'textTools', 'threadpoolctl', 'three-merge', 'tifffile', 'tinycss2', 'tldextract', 'toml', 'tomlkit', 'toolz', 'torch', 'torchvision', 'tornado', 'tqdm', 'traitlets', 'trio', 'trio-websocket', 'truststore', 'twine', 'Twisted', 'twisted-iocpsupport', 'typing_extensions', 'tzdata', 'tzlocal', 'uc-micro-py', 'ujson', 'Unidecode', 'urllib3', 'validators', 'values', 'w3lib', 'watchdog', 'wcwidth', 'webencodings', 'websocket-client', 'Werkzeug', 'whatthepatch', 'wheel', 'widgetsnbextension', 'win-inet-pton', 'wrapt', 'wsproto', 'xarray', 'xlwings', 'xyzservices', 'yapf', 'yarl', 'zict', 'zipp', 'zope.interface', 'zstandard'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='vueInit',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)